#ifndef CART_POLE_SYSTEM_DYNAMICS0__VISIBILITY_CONTROL_H_
#define CART_POLE_SYSTEM_DYNAMICS0__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define CART_POLE_SYSTEM_DYNAMICS0_EXPORT __attribute__ ((dllexport))
    #define CART_POLE_SYSTEM_DYNAMICS0_IMPORT __attribute__ ((dllimport))
  #else
    #define CART_POLE_SYSTEM_DYNAMICS0_EXPORT __declspec(dllexport)
    #define CART_POLE_SYSTEM_DYNAMICS0_IMPORT __declspec(dllimport)
  #endif
  #ifdef CART_POLE_SYSTEM_DYNAMICS0_BUILDING_LIBRARY
    #define CART_POLE_SYSTEM_DYNAMICS0_PUBLIC CART_POLE_SYSTEM_DYNAMICS0_EXPORT
  #else
    #define CART_POLE_SYSTEM_DYNAMICS0_PUBLIC CART_POLE_SYSTEM_DYNAMICS0_IMPORT
  #endif
  #define CART_POLE_SYSTEM_DYNAMICS0_PUBLIC_TYPE CART_POLE_SYSTEM_DYNAMICS0_PUBLIC
  #define CART_POLE_SYSTEM_DYNAMICS0_LOCAL
#else
  #define CART_POLE_SYSTEM_DYNAMICS0_EXPORT __attribute__ ((visibility("default")))
  #define CART_POLE_SYSTEM_DYNAMICS0_IMPORT
  #if __GNUC__ >= 4
    #define CART_POLE_SYSTEM_DYNAMICS0_PUBLIC __attribute__ ((visibility("default")))
    #define CART_POLE_SYSTEM_DYNAMICS0_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define CART_POLE_SYSTEM_DYNAMICS0_PUBLIC
    #define CART_POLE_SYSTEM_DYNAMICS0_LOCAL
  #endif
  #define CART_POLE_SYSTEM_DYNAMICS0_PUBLIC_TYPE
#endif
#endif  // CART_POLE_SYSTEM_DYNAMICS0__VISIBILITY_CONTROL_H_
// Generated 10-Sep-2023 13:10:20
// Copyright 2019-2020 The MathWorks, Inc.
